config/routes.rb
RailsconftutorialsBeeper::Application.routes.draw do
  root to: "alarms#index"
  resources :alarms, only: [:create, :destroy]

  get '/session', to: 'sessions#new', as: :login
  post '/session', to: 'sessions#create', as: :login
  delete '/session', to: 'sessions#destroy', as: :login
end

app/models/alarm.rb
class Alarm < ActiveRecord::Base
  validates_presence_of :service
  validates_presence_of :severity
  validates_inclusion_of :severity, in: %w(warning critical)

  def start_alarm
    self.status = true
    save
    yield(self) if block_given?
  end

  def stop_alarm
    self.status = false
    save!
    yield(self) if block_given?
  end
end

app/models/user.rb
class User

  def self.authenticate password
    return new if password == "supersecret"
  end
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  respond_to :json, :js

  before_filter :only => [:create] do
    @alarm = Alarm.find_by_service(params[:service]) || Alarm.create do |alarm|
      alarm.service  = params[:service]
      alarm.severity = 'warning'
    end
  end

  def index
    @alarms = Alarm.all
  end

  def create
    @alarm.start_alarm
    respond_with @alarm
  end

  def destroy
    @alarm = Alarm.find_by_service! params[:id]
    @alarm.stop_alarm
    respond_with @alarm
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authenticated?
    session[:authenticated] == true
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    flash.now[:notice] = "Please Log In"
  end

  def create
    if User.authenticate(params[:password])
      session[:authenticated] = true
      redirect_to root_path
    else
      flash.now[:error] = "Sorry, that's not right"
      render :new
    end
  end

  def destroy
    session.delete :authenticated
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/alarms/_alarms.html.erb
<% if @alarms.any? %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Service</th>
      <th>Severity</th>
      <th>Status</th>
      <th>Last Update</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @alarms.each do |alarm| -%>
      <tr>
        <td><%= alarm.service %></td>
        <td><%= alarm.severity %></td>
        <td><%= alarm.status %></td>
        <td><%= distance_of_time_in_words(alarm.updated_at, Time.now)%> ago</td>
        <td>
          <% if alarm.status %> 
            <%= link_to 'Close', alarm_path(id: alarm.service), 
            method: :delete, 
            remote: true, 
            disable_with: "Hold!",
            class: "btn btn-danger" %>
          <% end %>
      </td>
    <% end %>
  </tbody>
</table>
<% else %>
  <em>No alarms reported</em>
<% end %>

app/views/alarms/destroy.js.erb
<% @alarms ||= Alarm.all %>
$("#alarms").html("<%= j render partial: "alarms/alarms" %>");

app/views/alarms/index.html.erb
<div class="well">
  <h1>Alarms</h2>
</div>

<div id="alarms">
  <%= render partial: 'alarms' %>
</div>

app/views/beeper_notification/notify.txt.erb
We received the following notification:

----------------------------
<%= simple_format @text %>
----------------------------

Thanks!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsconftutorialsBeeper</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="<%= content_for(:wrapper_id) %>">
  <div class="container">
    <div class="clearfix">
      <div class="pull-right">
        <p>
          <%= link_to 'Log Out', login_path, method: :delete, class: 'btn' %>
        </p>
      </div>

      <% flash.each do |key, value| %>
        <div class="alert"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </div>
  </div>

</body>
</html>